Fix for scalar data fields and a new test
This does not pass for me but gives strange errors:

e.g.

AssertionError: array([ 1.,  2.]) is not array([ 1.,  2.])

This doesn’t make sense to me, since the arrays appear equivalent.